//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsMGMTDataAccess {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    public sealed partial class AppSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppSettings defaultInstance = ((AppSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppSettings())));
        
        public static AppSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=sportsappexceptions;AccountKey=f34SMxD" +
            "/59nQfbcDm9agxMfc2zcy7YIfCsSvr/IpOTSdNMBaafTvjCTzAg5lBHuik+xjl5XWHadv5s5IF/6QGw=" +
            "=;EndpointSuffix=core.windows.net")]
        public string blob {
            get {
                return ((string)(this["blob"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=tcp:carletonserver.database.windows.net,1433;Initial Catalog=SportsMGMTCap" +
            "Stone;Persist Security Info=False;User ID=carl;Password=5611S@ddle;MultipleActiv" +
            "eResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=3" +
            "0;")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
    }
}
